<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Log\UniqueMessageFilter $block */

?>

<div class="switcher">
    <input
        id="only_unique_messages_filter"
        type="checkbox"
        class="admin__control-checkbox"
        <?php
        if ($block->isChecked()) : ?>
            checked="checked"
        <?php
        endif; ?>
        onclick="setLocation('<?php
        /* @noEscape */ echo $block->getFilterUrl(); ?>');"
    >
    <label for="only_unique_messages_filter" class="admin__field-label">
        <span><?php
            /* @noEscape */ echo $block->getTitle(); ?></span>
    </label>
</div>
