<?php
/**
 * @var \M2E\Kaufland\Block\Adminhtml\Category\CategoryChooser $block
 */
?>

<div id='category_info_messaged_container'></div>

<div class="control-value">
    <?= /* @noEscape */ __(
        'You need to choose Categories for Products in order to list them on %channel_title.',
        [
            'channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle(),
        ],
    ) ?>
</div>

<div style="padding-top: 3px; font-weight: normal">
    <?= /* @noEscape */ __(
        'Products will be Listed using the same %channel_title Category.',
        [
            'channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle(),
        ],
    ) ?>
</div>

<div style="margin: 7px 52px">
    <b><?= /* @noEscape */ __('Category') ?></b>:
    <span id="category_path" style="font-style: italic; color: #808080">Not selected</span>
    &nbsp;<a href="javascript:void(0);" id="edit_category"><?= /* @noEscape */ __('Edit') ?></a>
    <br>
    <div id="attributes_wrapper" class="hidden">
        <b><?= /* @noEscape */ __('Attributes') ?></b>:
        <span id="attributes_required" class="required hidden">*</span>
        <span id="attributes_counts" style="font-style: italic; color: #808080">0/0</span>
        &nbsp<a href="javascript:void(0);" id="edit_attributes"><?= /* @noEscape */ __('Edit') ?></a>
    </div>
</div>
<label style="margin: 0 52px; display: none;" class="mage-error" id="same_product_type_error">
    <?= /* @noEscape */ __('Please select Category.') ?>
</label>

<script>
    require([
        'Kaufland/Category/Chooser'
    ], function() {
        <?php if($block->getSelectedCategory() !== null): ?>
        KauflandCategoryChooserObj.setSelectedCategory(<?= /* @noEscape */ $block->getSelectedCategory() ?>);
        KauflandCategoryChooserObj.confirmCategory()
        <?php endif; ?>
        KauflandCategoryChooserObj.initObservers();
    });
</script>
