<?php

/** @var \M2E\Kaufland\Block\Adminhtml\Category\Chooser\Tab\Search $this */

?>

<div id="category_search" data-bind="scope: 'category_search'">
    <input id='query'
           class='search-input'
           type='text'
           placeholder="<?= /* @noEscape */ __('Enter keyword(s) or Category ID...') ?>"
           data-bind="textInput: query, event: {keypress: searchOnEnter}">
    <button class='action primary search-btn' data-bind="click: search"><?= /* @noEscape */ __('Search') ?></button>
    <a class="reset-input" data-bind="click: reset" style="margin-left: 23px;"><?= /* @noEscape */ __('Reset') ?></a>

    <div id="search_results_container">
        <div data-bind='if: hasMoreCategories'>
            <div class='message message-notice notice'>
                <div data-ui-id='messages-message-notice'>
                    <?= /* @noEscape */
                    __(
                        'Showing the top 20 matching %channel_title categories below. For more options,
                     please refine your search with a more specific query.',
                        ['channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle()]
                    ) ?>
                </div>
            </div>
        </div>
        <table id="search_results_table" class="search_results_table">
        <tbody data-bind="foreach: {data: foundCategories, as: 'category', noChildContext: true}">
            <tr>
                <td>
                    <span data-bind="text: category.name"></span>
                </td>
                <td style='text-align: right'>
                    <a class='choice-category'
                       data-bind="attr: {'data-category-id': category.id},
   click: selectCategory.bind($data, category.id)"><?= /* @noEscape */ __('Select') ?></a>
                </td>
            </tr>
        </tbody>
        <tr data-bind="if: !hasFoundCategories">
            <td colspan="2">
                <span data-bind="if: searched"><?= /* @noEscape */ __('No matching Categories are found.') ?></span>
                <span data-bind="ifnot: searched"><?= /* @noEscape */ __('Enter keyword(s) or Category ID to search.') ?></span>
            </td>
        </tr>
    </table>
    </div>
</div>


