<?php

/** @var \M2E\Kaufland\Block\Adminhtml\ControlPanel\Tabs\Command\Group $block */

?>

<?php
foreach ($block->commands as $index => $command) : ?>
    <table class="controlPanel-reflection-container">
        <tr>
            <td class="group_number_td"><b><?php
                    echo $index + 1; ?>.</b></td>
            <td class="group_separator">|</td>
            <td>
                <?= $block->getCommandLauncherHtml($command); ?>
            </td>
        </tr>

        <?php
        if ($command['new_line']) : ?>
            <tr>
                <td colspan="3">
                    <hr/>
                </td>
            </tr>
        <?php
        endif; ?>

    </table>

<?php
endforeach; ?>
