<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Listing\Log\ErrorsSummary $block */

?>

<div class="errors_summary_title">
    <?php
    /* @noEscape */ echo $block->__('Errors Summary'); ?>
    <a href="javascript:void(0);" onclick="$('listing_container_errors_summary').hide();" title="<?php
    /* @noEscape */ echo $block->__('Close'); ?>">
        <span class="errors_summary_close icon-close"></span>
    </a>
</div>

<div class="errors_summary_content">

    <?php
    foreach ($block->errors as $error) { ?>
        <div class="errors_summary_line">
            <div class="errors_summary_type">
                <?php
                if ((int)$error['count_products'] == 0) { ?>
                    <?php
                    /* @noEscape */ echo $block->__('Global'); ?>
                <?php
                } else { ?>
                    <?php
                    /* @noEscape */ echo (int)$error['count_products']; ?>
                    <?php
                    /* @noEscape */ echo $block->__('Product(s)'); ?>
                <?php
                } ?>
            </div>
            <div class="errors_summary_text">
                <?php
                /* @noEscape */ echo $error['description']; ?>
            </div>
        </div>

    <?php
    } ?>

</div>
