<?php
/** @var \M2E\Kaufland\Block\Adminhtml\ControlPanel\Inspection\Cron $block */ ?>

<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php
                echo $block->__('Last Run'); ?>: </label>
        </td>
        <?php
        $style = '';
        if ($block->cronIsNotWorking) {
            $style = ' style="color: red"';
        }
        ?>
        <td class="value">
            <span<?php
            echo $style; ?>><?php
                echo $block->cronLastRunTime ?></span>
            <?php
            if ($block->cronIsNotWorking) : ?>
                &nbsp;<a href="<?php
                echo 'https://help.m2epro.com/support/solutions/articles/9000200879'; ?>" target="_blank"><?php
                    echo $block->__('[read more]'); ?></a>
            <?php
            endif; ?>
        </td>
    </tr>

    <?php
    if (!$block->getData('is_support_mode') && $block->isMagentoCronDisabled) : ?>
        <tr>
            <td class="label">
                <label><?php
                    echo $block->__('Magento Cron State'); ?>: </label>
            </td>
            <td class="value" style="color: red;">
                <?php
                echo $block->__('Disabled by Developer'); ?>
            </td>
        </tr>
    <?php
    endif; ?>

</table>
