<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Magento\Tabs\AbstractHorizontalStaticTabs $block */
$tabs = $block->getTabs();

if (empty($tabs)) {
    return;
}
?>

<div class="kaufland-tabs-horizontal kaufland-tabs-horizontal-static">
    <div class="ui-tabs ui-corner-all ui-widget ui-widget-content">
        <ul class="tabs-horiz" style="display: block;">
            <?php
            foreach ($tabs as $tab): ?>
                <li class="ui-state-default ui-corner-top  <?= /* @noEscape */
                $tab['is_active'] ? 'ui-state-active' : ''; ?>">
                    <a href="<?= /* @noEscape */
                    $tab['url']; ?>" title="<?= /* @noEscape */
                    $tab['title']; ?>" class="tab-item-link ui-tabs-anchor">
                        <span><?= /* @noEscape */
                            $tab['content']; ?></span>
                    </a>
                </li>
            <?php
            endforeach; ?>
        </ul>
    </div>
</div>
