<?php
/** @var \M2E\Kaufland\Block\Adminhtml\Listing\Product\ShowOthersListingsProductsFilter $block */
?>

<style type="text/css">

    div.switcher {
        margin-bottom: 30px;
        padding: 1.5em;
    }

    div.switcher span.label {
        font-weight: bold;
    }

    div.switcher span.value {
        color: #8e9393;
    }

    .tips_show_products_others_listings_filter {
        display: inline-block;
    }

</style>

<div class="switcher Kaufland-box-style">
    <input
        id="switcher_show_products_others_listings_filter"
        type="checkbox"
        class="admin__control-checkbox"
        <?php if ($block->isChecked()) :
            ?>checked="checked"<?php
        endif; ?>
        onclick="setLocation('<?php /* @noEscape */ echo $block->getFilterUrl(); ?>');"
    >
    <label for="switcher_show_products_others_listings_filter" class="admin__field-label">
        <span><?php /* @noEscape */ echo __('Show Products presented in other %channel_title Listings', ['channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle()]); ?></span>
    </label>
</div>
