<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Wizard\InstallationKaufland\Installation\ListingTutorial\Content $block */

?>

<div class="wizard_block">
    <h2>
        <?php
        echo __(
            'Congratulations! You have registered your M2E Kaufland Extension and linked your Kaufland Account to it.'
        ); ?>
    </h2>

    <p>
        <?php
        echo __('The next step involves creating your first M2E Kaufland Listing.'); ?>
    </p>
    <br/>

    <p>
        <?php
        echo __(
            'M2E Kaufland Listing is a group of Magento Products combined under specific sets of rules. <br/>These are the
                    Products which will be offered as Kaufland Items by a Seller on a particular Storefront.'
        ); ?>
    </p>
    <br/>

    <p>
        <?php
        echo __(
            'Click on the <strong>Create First Listing</strong> button to proceed.
             Or click on the <strong>Skip</strong> button if you want to create your first listing later.'
        ); ?>
    </p>
</div>
