<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Kaufland\Template\Category\Chooser\Specific\Form\Renderer\Dictionary $this */

/** @var \M2E\Kaufland\Block\Adminhtml\Kaufland\Template\Category\Chooser\Specific\Form\Element\Dictionary $element */
$element = $this->getElement();
?>

<table
    data-specific-scope="<?= $element->getId() ?>"
    class="specific-table data-grid data-grid-not-hovered"
    style="width: 100%"
>
    <thead>
    <tr class="headings">
        <th class="data-grid-th" style="width: 30%;"><?= __('Name'); ?></th>
        <th class="data-grid-th" style="width: 30%;"><?= __('Mode'); ?></th>
        <th class="data-grid-th" style="width: 40%;"><?= __('Value'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($element->getSpecifics() as $index => $specific) { ?>
        <tr style="height: 25px;">
            <td style="vertical-align:top;">
                <?php
                echo $element->getAttributeIdHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getAttributeTitleHiddenHtml($index, $specific);
                echo $element->getAttributeNickHiddenHtml($index, $specific);
                echo $element->getAttributeDescriptionHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getAttributeTypeHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getModeHtml($index); ?>
                <?php
                echo $element->getAttributeTitleLabelHtml($index, $specific); ?>
                <?php
                echo $element->getAttributeDescriptionHintHtml($specific); ?>
            </td>
            <td style="vertical-align:top;">
                <?php
                echo $element->getValueModeSelectHtml($index, $specific); ?>
            </td>
            <td style="width: 100%; vertical-align:top; text-align: left;">
                <?php
                echo $element->getValueKauflandRecommendedHtml($index, $specific); ?>
                <?php
                echo $element->getValueCustomValueHtml($index, $specific); ?>
                <?php
                echo $element->getValueCustomAttributeHtml($index, $specific); ?>
            </td>
        </tr>
    <?php
    } ?>
    </tbody>
</table>
