<?php
/** @var \Magento\Backend\Block\Template $block */
$parentBlock = $block->getParentBlock();
?>

<script>
    require([
        'Kaufland/Category/Attribute/Validation/Grid'
    ], function(Grid) {
        if (!window.kauflandGridInitialized) {
            new Grid({
                grid_id: '<?= $block->escapeHtml($parentBlock->getGridSelectorId()) ?>',
                progress_bar_id: '<?= $block->escapeHtml($parentBlock->getProgressBarSelectorId()) ?>',
                validate_url: '<?= $block->escapeHtml($parentBlock->getValidateUrl()) ?>',
                reload_grid_url: "<?= $block->escapeHtml($parentBlock->getReloadGridUrl()) ?>"
            });

            window.kauflandGridInitialized = true;
        }
    });
</script>
