<?php

/** @var \M2E\Kaufland\Block\Adminhtml\Listing\Wizard\Product\NewProductPopup $block */

?>
<div id="search_ean_new_product_popup">
    <p>
        <?= /* @noEscape */ __(
            'Would you like to create new %channel_title products for your Magento products that were not found
        in the %channel_title catalog based on the provided Product Identifiers (EAN)?',
            ['channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle()]
        ) ?>
    </p>
</div>
