<?php

/** @var \M2E\Kaufland\Block\Adminhtml\Mapping\Tabs\AttributeMapping $block */

echo $block
    ->getLayout()
    ->createBlock(\M2E\Kaufland\Block\Adminhtml\HelpBlock::class)
    ->setData([
        'content' => (string)__(
            'On this page, the attribute mapping demonstrates the connection between your channel
                category attributes and the corresponding Magento Product attributes. This mapping guarantees that
                the correct Magento attributes are consistently associated with each category attribute. You can edit
                 the saved mapping if a different Magento value is more appropriate for a certain category parameter.'
        ),
    ])->toHtml();
?>

<form method="post" novalidate="novalidate" enctype="multipart/form-data">
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th kaufland_channel_attribute"><?= /* @noEscape */ __(
                    '%channel_title Attribute',
                    [
                        'channel_title' => \M2E\Kaufland\Helper\Module::getChannelTitle(),
                    ]
                ) ?></th>
            <th class="data-grid-th"><?= /* @noEscape */ __('Magento Attribute') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($block->getMappedAttributes() as $mappedAttribute) : ?>
            <tr>
                <td><?= /* @noEscape */ $mappedAttribute->getChannelAttributeTitle() ?></td>
                <td><?= /* @noEscape */ $block->makeMagentoAttributesDropDownHtml($mappedAttribute) ?></td>
            </tr>
        <?php
        endforeach; ?>
        </tbody>
    </table>
</form>
