<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\ControlPanel\Tabs\Cron $this */
?>

<div class="entry-edit group_container_summary">

    <div class="control_panel_head_container">
        <h4><?php echo __('Run Task'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="hor-scroll">

            <table class="form-list" cellspacing="0" cellpadding="0">

                <tr>
                    <td class="label">
                        <label><?php echo __('Task Name'); ?>: </label>
                    </td>

                    <td class="value">
                        <select id="task_code" name="task_code" style="width: 400px;">
                            <option value=""><?php echo __('-- run all --'); ?></option>
                            <?php foreach ($this->tasks as $optgroup => $tasks) : ?>
                                <optgroup label="<?php echo $optgroup; ?>">
                                    <?php foreach ($tasks as $taskCode => $taskTitle) : ?>
                                        <option value="<?php echo rawurlencode($taskCode); ?>"><?php echo $taskTitle; ?></option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        </select>
                    </td>

                    <td class="value">
                        <a class="action-default scalable add" onclick="window.open('<?php echo $block->getUrl('*/controlPanel_cron/run', ['_query' => ['task_code' => 'task-plx']]); ?>'.replace('task-plx', $('task_code').value));" href="javascript:void(0);" style="display: inline !important; margin-left: 10px;"><?php echo __('Run') ?></a>
                    </td>
                </tr>

            </table>

        </div>
    </div>

</div>
