<?php

// @codingStandardsIgnoreFile

/**
 * @var \M2E\Kaufland\Block\Adminhtml\ControlPanel\Tabs\Overview $block
 */

?>

<style>
    .fieldset-wrapper .form-list {
        font-size: 13px;
    }

    .fieldset-wrapper td.label {
        width: 220px !important;
    }
</style>

<div class="col-m-4 controlPanel__block_container">
    <div class="fieldset-wrapper" id="magento_block_control_panel_info_module">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?= __('Information'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?= $block->getChildHtml('actual_info') ?>
            </div>
        </div>

    </div>

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_location">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?= __('License'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?= $block->getChildHtml('license_info') ?>
            </div>
        </div>

    </div>
</div>

<div class="col-m-4 controlPanel__block_container">
    <div class="fieldset-wrapper" id="magento_block_control_panel_database_general">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?= __('Database'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?= $block->getChildHtml('database_general') ?>
            </div>
        </div>

    </div>
</div>

<div class="col-m-4 controlPanel__block_container">

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_cron">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?= __('Cron'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?= $block->getChildHtml('cron_info') ?>
            </div>
        </div>

    </div>

    <div class="fieldset-wrapper" id="magento_block_control_panel_info_cron">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <h4><?= __('Version Info'); ?></h4>
        </div>

        <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
            <div class="hor-scroll">
                <?= $block->getChildHtml('version_info') ?>
            </div>
        </div>

    </div>

</div>
