<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\Order\NotCreatedFilter $block */

?>

<div class="switcher">
    <input
        id="switcher_not_created_filter"
        type="checkbox"
        class="admin__control-checkbox"
        <?php
        if ($block->isChecked()) :
        ?>checked="checked"<?php
    endif; ?>
        onclick="setLocation('<?php
        /* @noEscape */ echo $block->getFilterUrl(); ?>');"
    >
    <label for="switcher_not_created_filter" class="admin__field-label">
        <span><?php
            /* @noEscape */ echo $block->__('No Magento Order Created'); ?></span>
    </label>
</div>
