<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */ ?>

<?php
if ($block->getData('is_maintenance_due_low_magento_version')) : ?>
    <p>M2E Kaufland has been placed on maintenance mode because your current Magento version is no longer supported
        and compatible with the latest version of M2E Kaufland extension.</p>
    <p>To restore the functionality, we recommend considering one of the following conditions:</p>
    <ol style="margin-left: 30px; max-width: 800px;">
        <li>
            <p>Upgrade your Magento:</p>
            <p>
                Upgrading your Magento to the latest stable version will not only ensure
                compatibility with the latest M2E Kaufland version but also provide access to new features,
                performance enhancements, and security patches.
            </p>
        </li>
    </ol>
    <p>If you require any guidance or have questions to clarify, you are welcome to reach out
        to our support team at <a href="mailto:support@m2epro.com">support@m2epro.com</a></p>
<?php
else : ?>
    <p>Inventory and Order synchronization is not running. The Module interface is unavailable. M2E Kaufland can be
        put under maintenance automatically due to the following reasons:</p>

    <ul style="margin-left: 30px; max-width: 800px;">
        <li>
            <p>Module installation failed, e.g. due to the incorrect installation via Magento Component Manager,
                incompatibility of Magento and its Modules, or other technical issues.</p>
        </li>
        <li>
            <p>Module upgrade failed, e.g. due to the improper M2E Kaufland tables updating or php
                %magento2_installation_dir%/bin/magento setup:upgrade command running.</p>
        </li>
    </ul>

    <p>Please contact Support at <a href="mailto:support@m2epro.com">support@m2epro.com</a> to resolve the issue.</p>
<?php
endif; ?>
