<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Kaufland\Block\Adminhtml\PageHelpLink $block */

?>

<div class="Kaufland-page-help-link Kaufland-field-tooltip-to-right admin__field-tooltip">
    <a class="admin__field-tooltip-action" href="<?php
    echo $block->getPageHelpLink(); ?>" target="_blank"></a>
    <div class="admin__field-tooltip-content">
        <?php
        echo $block->__('Click here to get help for this page.'); ?>
    </div>
</div>
