<?php

// @codingStandardsIgnoreFile

/** @var $block \M2E\Kaufland\Block\Adminhtml\Listing\View\Switcher */

?>

<select name="listing_view_mode_switcher" id="listing_view_mode_switcher" class="admin__control-select">
    <?php
    foreach ($block->getItems() as $item) : ?>
        <option value="<?php
        /* @noEscape */ echo \M2E\Core\Helper\Data::escapeHtml($item['value']) ?>" <?php
                if ($block->getCurrentViewMode() == $item['value']) :
                ?>selected="selected"<?php
        endif; ?>><?php
            /* @noEscape */ echo \M2E\Core\Helper\Data::escapeHtml($item['label']); ?></option>
    <?php
    endforeach; ?>
</select>
