<?php

/** @var \M2E\Kaufland\Block\Adminhtml\Order\Edit\ShippingAddress $block */

?>

<table class="order-info form-list">
    <tbody>

    <tr>
        <td class="label"><?= /* @noEscape */ __('Name'); ?></td>
        <td class="value">
            <strong>
                <?= \M2E\Core\Helper\Data::escapeHtml($block->getBuyerName()) ?>
            </strong>
        </td>
    </tr>

    <tr>
        <td class="label"><?= /* @noEscape */ __('User ID'); ?></td>
        <td class="value">
            <strong>
                <?= \M2E\Core\Helper\Data::escapeHtml($block->getOrder()->getBuyerUserId()) ?>
            </strong>
        </td>
    </tr>

    <tr>
        <td class="label"><?= /* @noEscape */ __('Email'); ?></td>
        <td class="value">
            <strong>
                <?php
                if ($block->getOrder()->getBuyerEmail() != '') { ?>
                    <?php
                    if (stripos($block->getOrder()->getBuyerEmail(), 'Invalid Request') !== false) { ?>
                        &lt;<?= /* @noEscape */ __('Private Restriction'); ?>&gt;<br/>
                    <?php
                    } else { ?>
                        &lt;<?= \M2E\Core\Helper\Data::escapeHtml($block->getOrder()->getBuyerEmail()); ?>&gt;<br/>
                    <?php
                    } ?>
                <?php
                } ?>
            </strong>
        </td>
    </tr>
    <tr>
        <td class="label"><?= /* @noEscape */ __('Address'); ?></td>
        <td class="value">
            <strong>

                <?php
                if (!empty($block->getShippingAddress())) : ?>
                    <?php
                    if (!empty($block->getShippingAddress()['recipient_name'])): ?>
                        <?= \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['recipient_name']); ?>
                    <?php
                    endif; ?>

                    <?php
                    if (!empty($block->getShippingAddress()['company_name'])): ?>
                        <br/><?= \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['company_name']); ?>
                    <?php
                    endif; ?>

                    <?php
                    if (!empty($block->getShippingAddress()['street'])) : ?>
                        <br/><?= \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['street']); ?>
                    <?php
                    endif;
                    if (!empty($block->getShippingAddress()['house_number'])) : ?>
                        <?= \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['house_number']); ?>
                    <?php
                    endif; ?>

                    <?php
                    if (!empty($block->getShippingAddress()['city'])) : ?>
                        <?php
                        $addressData = array_filter([
                            $block->getShippingAddress()['city'],
                            $block->getShippingAddress()['state'] ?? '',
                            $block->getShippingAddress()['postal_code'],
                        ]);
                        ?>
                        <br/><?= \M2E\Core\Helper\Data::escapeHtml(implode(', ', $addressData)) ?>
                    <?php
                    endif; ?>

                    <?php
                    if (!empty($block->getShippingAddress()['country_name'])) : ?>
                        <br/>
                        <?php
                        if (!empty($block->getShippingAddress()['country_name'])) {
                            echo \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['country_name']);
                        } else {
                            echo \M2E\Core\Helper\Data::escapeHtml($block->getShippingAddress()['country_code']);
                        }
                        ?>
                    <?php
                    endif; ?>

                    <?php
                    if (
                        !empty($block->getShippingAddress()['phone']) && stripos(
                            $block->getShippingAddress()['phone'],
                            'Invalid Request'
                        ) === false
                    ) : ?>
                        <br/><?= 'T: ' . \M2E\Core\Helper\Data::escapeHtml(
                            $block->getShippingAddress()['phone']
                        ); ?>
                    <?php
                    endif; ?>

                <?php
                endif; ?>

            </strong>
        </td>
    </tr>
    </tbody>
</table>
